# Generated by Django 4.2.3 on 2023-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placesimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesimage',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Изображение места'),
        ),
    ]
