# Generated by Django 4.2.3 on 2023-09-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placesimage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placesimage',
            old_name='title',
            new_name='position',
        ),
    ]
