# Generated by Django 4.2.3 on 2023-09-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_rename_title_placesimage_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesimage',
            name='position_1',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
