# Generated by Django 4.2.3 on 2023-09-03 11:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_placesimage_position_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placesimage',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Длинное описание'),
        ),
    ]
