# Generated by Django 4.2.3 on 2023-09-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_title_alter_placesimage_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
