# Generated by Django 4.2.3 on 2023-09-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_placesimage_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('longitude', 'latitude')},
        ),
    ]
